// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9dzB_EXIGHFkyKZSg7v4bN_zV1GsVg14',
    appId: '1:582344887169:android:a0e6a5426d867b172cf680',
    messagingSenderId: '582344887169',
    projectId: 'app1-c9e39',
    databaseURL: 'https://app1-c9e39-default-rtdb.firebaseio.com',
    storageBucket: 'app1-c9e39.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZBfdfuUhAhY_eCUrCG0QShDV73Sb_SRs',
    appId: '1:582344887169:web:01d99c47ce55cf092cf680',
    messagingSenderId: '582344887169',
    projectId: 'app1-c9e39',
    authDomain: 'app1-c9e39.firebaseapp.com',
    databaseURL: 'https://app1-c9e39-default-rtdb.firebaseio.com',
    storageBucket: 'app1-c9e39.firebasestorage.app',
    measurementId: 'G-0VT6948YHF',
  );

}